# 模块跟目录
path: modules

# 配置主题
theme: 孩子王

# 输出文件
# .min.js 代表输出压缩后的js文件
out:
  - ui/ui.css
  - ui/ui.js
  - demos/css/ui.min.css
  - demos/js/ui.min.js

# 模块列表
modules:
  - reset
  - tool
  - margin
  - line
  - column
  - text
  - link
  - button
  - border
  - input
  - select
  - table
  # - list
  - tab
  - label
  - tip
  - notice
  - page
  # - popup
  - progress
  # - calendar
  - form
  - textarea
  # - step
  - banner
  - scrollhook
  - scrollto
  - checkboxradio
  - date
  - relative
  - maxtext
  - autoarea
  - shownone
  - modal
  - template
  - multiline
  - birthday
  - loadjs
  - idcard
  - week
  - placeholder
  - demo
